version: '3'
services:
  web:
    build:
      context: .
    ports:
      - "4000:4000"
    volumes:
     - .:/app
    command: mix phx.server
    depends_on:
     - postgres
     - orientdb
    # entrypoint: ./wait-for-postgres.sh postgres `mix phx.server`

  postgres:
    image: postgres
    volumes:
      - ./db/postgres/data:/var/lib/postgresql/data

  orientdb:
    image: orientdb
    ports:
      - 2424:2424
      - 2480:2480
    volumes:
      - ./db/orientdb/databases:/orientdb/databases
    environment:
      - ORIENTDB_ROOT_PASSWORD=root